//go:build !ignore_autogenerated

/*
Copyright 2025 bensonphillipsiv.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitStatus) DeepCopyInto(out *CommitStatus) {
	*out = *in
	if in.Date != nil {
		in, out := &in.Date, &out.Date
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitStatus.
func (in *CommitStatus) DeepCopy() *CommitStatus {
	if in == nil {
		return nil
	}
	out := new(CommitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureCycleStatus) DeepCopyInto(out *FailureCycleStatus) {
	*out = *in
	if in.CooldownStartTime != nil {
		in, out := &in.CooldownStartTime, &out.CooldownStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureCycleStatus.
func (in *FailureCycleStatus) DeepCopy() *FailureCycleStatus {
	if in == nil {
		return nil
	}
	out := new(FailureCycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sibleWorkflow) DeepCopyInto(out *K8sibleWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sibleWorkflow.
func (in *K8sibleWorkflow) DeepCopy() *K8sibleWorkflow {
	if in == nil {
		return nil
	}
	out := new(K8sibleWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sibleWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sibleWorkflowList) DeepCopyInto(out *K8sibleWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K8sibleWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sibleWorkflowList.
func (in *K8sibleWorkflowList) DeepCopy() *K8sibleWorkflowList {
	if in == nil {
		return nil
	}
	out := new(K8sibleWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sibleWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sibleWorkflowSpec) DeepCopyInto(out *K8sibleWorkflowSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Apply.DeepCopyInto(&out.Apply)
	if in.Reconcile != nil {
		in, out := &in.Reconcile, &out.Reconcile
		*out = new(PlaybookSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureCycleCooldown != nil {
		in, out := &in.FailureCycleCooldown, &out.FailureCycleCooldown
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sibleWorkflowSpec.
func (in *K8sibleWorkflowSpec) DeepCopy() *K8sibleWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(K8sibleWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sibleWorkflowStatus) DeepCopyInto(out *K8sibleWorkflowStatus) {
	*out = *in
	if in.ApplyCommit != nil {
		in, out := &in.ApplyCommit, &out.ApplyCommit
		*out = new(CommitStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReconcileCommit != nil {
		in, out := &in.ReconcileCommit, &out.ReconcileCommit
		*out = new(CommitStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingPlaybooks != nil {
		in, out := &in.PendingPlaybooks, &out.PendingPlaybooks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSuccessfulRun != nil {
		in, out := &in.LastSuccessfulRun, &out.LastSuccessfulRun
		*out = new(PlaybookRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastFailedRun != nil {
		in, out := &in.LastFailedRun, &out.LastFailedRun
		*out = new(PlaybookRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyScheduleStatus != nil {
		in, out := &in.ApplyScheduleStatus, &out.ApplyScheduleStatus
		*out = new(ScheduleStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReconcileScheduleStatus != nil {
		in, out := &in.ReconcileScheduleStatus, &out.ReconcileScheduleStatus
		*out = new(ScheduleStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureCycleStatus != nil {
		in, out := &in.FailureCycleStatus, &out.FailureCycleStatus
		*out = new(FailureCycleStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sibleWorkflowStatus.
func (in *K8sibleWorkflowStatus) DeepCopy() *K8sibleWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(K8sibleWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookRunStatus) DeepCopyInto(out *PlaybookRunStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookRunStatus.
func (in *PlaybookRunStatus) DeepCopy() *PlaybookRunStatus {
	if in == nil {
		return nil
	}
	out := new(PlaybookRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookSpec) DeepCopyInto(out *PlaybookSpec) {
	*out = *in
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookSpec.
func (in *PlaybookSpec) DeepCopy() *PlaybookSpec {
	if in == nil {
		return nil
	}
	out := new(PlaybookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleStatus) DeepCopyInto(out *ScheduleStatus) {
	*out = *in
	if in.LastScheduledTime != nil {
		in, out := &in.LastScheduledTime, &out.LastScheduledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleStatus.
func (in *ScheduleStatus) DeepCopy() *ScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}
